name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
         
          pip install -r requirements.txt
        working-directory: ./  

      - name: Deploy to Streamlit Sharing
        run: |
          pip install streamlit
          streamlit deploy data.py --secrets .streamlit/secrets.toml  # Use the path to secrets.toml
        working-directory: ./  
        env:
          STREAMLIT_SECRETS: ${{ secrets.STREAMLIT_SECRETS }}
