name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pip install -r requirements.txt
          pylint data.py
        working-directory: ./  
      
      - name: Run Pytest
        run: |
          pip install pytest
          pytest test_data.py 
        working-directory: ./ 


      - name: Build Docker image
        run: docker build -t my-streamlit-app:latest .
        working-directory: .  

      - name: Push Docker image to Docker Hub
        run: |
        
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag my-streamlit-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-streamlit-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-streamlit-app:latest
          
          
      - name: Deploy to Docker
        run: docker run -d -p 8503:8501 ${{ secrets.DOCKERHUB_USERNAME }}/my-streamlit-app:latest

